"""empty message

Revision ID: 04c2f9f0142f
Revises: 
Create Date: 2024-08-29 14:43:45.646070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c2f9f0142f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('picture', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='public'
    )
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('toots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=280), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['original_id'], ['public.toots.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['public.toots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liker_id', sa.Integer(), nullable=True),
    sa.Column('liked_toot_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_toot_id'], ['public.toots.id'], ),
    sa.ForeignKeyConstraint(['liker_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes', schema='public')
    op.drop_table('toots', schema='public')
    op.drop_table('messages', schema='public')
    op.drop_table('follows')
    op.drop_table('users', schema='public')
    # ### end Alembic commands ###
