"""empty message

Revision ID: 72a6306c3893
Revises: 
Create Date: 2023-08-06 09:38:24.691385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a6306c3893'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name='follows_followee_id_fkey'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_follower_id_fkey'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id', name='follows_pkey')
    )
    # ### end Alembic commands ###
