"""empty message

Revision ID: 915a8a49744d
Revises: 58ab773f1227
Create Date: 2023-08-13 15:10:06.955768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '915a8a49744d'
down_revision = '58ab773f1227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'toots', ['original_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('original_id')

    # ### end Alembic commands ###
