"""empty message

Revision ID: e0be214d2572
Revises: 04c2f9f0142f
Create Date: 2024-08-29 14:44:27.349300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0be214d2572'
down_revision = '04c2f9f0142f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint('follows_followee_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('follows_follower_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['followee_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('likes_liked_toot_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('likes_liker_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['liker_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'toots', ['liked_toot_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('messages_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('messages_receiver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['receiver_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['sender_id'], ['id'], referent_schema='public')

    with op.batch_alter_table('toots', schema=None) as batch_op:
        batch_op.drop_constraint('toots_original_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('toots_parent_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('toots_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'toots', ['original_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'], referent_schema='public')
        batch_op.create_foreign_key(None, 'toots', ['parent_id'], ['id'], referent_schema='public')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toots', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('toots_author_id_fkey', 'users', ['author_id'], ['id'])
        batch_op.create_foreign_key('toots_parent_id_fkey', 'toots', ['parent_id'], ['id'])
        batch_op.create_foreign_key('toots_original_id_fkey', 'toots', ['original_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('messages_receiver_id_fkey', 'users', ['receiver_id'], ['id'])
        batch_op.create_foreign_key('messages_sender_id_fkey', 'users', ['sender_id'], ['id'])

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('likes_liker_id_fkey', 'users', ['liker_id'], ['id'])
        batch_op.create_foreign_key('likes_liked_toot_id_fkey', 'toots', ['liked_toot_id'], ['id'])

    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('follows_follower_id_fkey', 'users', ['follower_id'], ['id'])
        batch_op.create_foreign_key('follows_followee_id_fkey', 'users', ['followee_id'], ['id'])

    # ### end Alembic commands ###
